#!/usr/bin/env bash

# bash script.

# exit if any single line fails.
# set the `-e` flag.
set -e

# function to clean up the deploy branch.

function cleanup_at_exit {
  # return to master branch
  git checkout master
  
  # remove the deploy branch
  git branch -D deploy
}
trap cleanup_at_exit EXIT

# checks out a new branch called "deploy", matching the name of the heroku remote branch 

git checkout -b deploy

# webpack will run in "production mode"
webpack -p

# "force" add the otherwise gitignored build files
git add -f public/bundle.js public/bundle.js.map

# create a commit, even if nothing changed
git commit --allow-empty -m 'Deploying'

# push local "deploy" branch to the "master" branch on heroku
git push --force heroku deploy:master
